---
# Build the ESPHome binary firmware
# And deploy it to Github Pages.
name: Build firmware

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: "üõ†Ô∏è ESPHome firmware"
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      files: home_assistant_glow.yaml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
